name: Testing Linters - Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-test:Eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Projeto
        uses: actions/checkout@v3

      - name: Instala Node.js
        uses: actions/setup-node@v3

      - name: Instalação das Libs
        run: npm install

      - name: Roda o EsLint
        run: npm run test:lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-test:StyleLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Projeto
        uses: actions/checkout@v3

      - name: Instala Node.js
        uses: actions/setup-node@v3

      - name: Instalação das Libs
        run: npm install

      - name: Roda o EsLint
        run: npm run test:style
